custom: [https://www.guidestar.org/profile/92-3556562]
# 
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
liberapay: # Replace with a single Liberapay username
